#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""TTS 后端常量。"""

# ── 服务商标识 ──────────────────────────────────────────────────────

TTS_API_PROVIDER_CARTESIA = "Cartesia"
TTS_API_PROVIDER_VOLCENGINE = "Volcengine"
TTS_API_PROVIDERS = (TTS_API_PROVIDER_CARTESIA, TTS_API_PROVIDER_VOLCENGINE)
DEFAULT_TTS_API_PROVIDER = TTS_API_PROVIDER_CARTESIA

# ── 生成模式（后端） ────────────────────────────────────────────────

TTS_BACKEND_CARTESIA_BYTES = "Cartesia Bytes"
TTS_BACKEND_CARTESIA_REALTIME = "Cartesia Realtime"
TTS_BACKEND_VOLCENGINE_STREAMING = "Volcengine Streaming"

TTS_BACKENDS = (
    TTS_BACKEND_CARTESIA_BYTES,
    TTS_BACKEND_CARTESIA_REALTIME,
    TTS_BACKEND_VOLCENGINE_STREAMING,
)
DEFAULT_TTS_BACKEND = TTS_BACKEND_CARTESIA_BYTES

# 每个服务商的默认生成模式
DEFAULT_BACKEND_BY_PROVIDER: dict[str, str] = {
    TTS_API_PROVIDER_CARTESIA: TTS_BACKEND_CARTESIA_BYTES,
    TTS_API_PROVIDER_VOLCENGINE: TTS_BACKEND_VOLCENGINE_STREAMING,
}

# 按服务商分组的生成模式（设置 UI 按 provider 过滤用）
TTS_BACKENDS_BY_PROVIDER: dict[str, tuple[str, ...]] = {
    TTS_API_PROVIDER_CARTESIA: (TTS_BACKEND_CARTESIA_BYTES, TTS_BACKEND_CARTESIA_REALTIME),
    TTS_API_PROVIDER_VOLCENGINE: (TTS_BACKEND_VOLCENGINE_STREAMING,),
}
