#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""TTS 后端常量。"""

TTS_BACKEND_CARTESIA_BYTES = "Cartesia Bytes"
TTS_BACKEND_CARTESIA_REALTIME = "Cartesia Realtime"
TTS_BACKENDS = (TTS_BACKEND_CARTESIA_BYTES, TTS_BACKEND_CARTESIA_REALTIME)
DEFAULT_TTS_BACKEND = TTS_BACKEND_CARTESIA_BYTES
