name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build
        run: .\compile.ps1 -Clean -NoPause

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/Wordy.exe
          generate_release_notes: true
